## Numpy简介

### 1. Numpy基本属性

In [2]:
import numpy as np

In [18]:
# 利用np.arange()创建一个包含15个元素的Numpy数组对象
arr = np.arange(15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [17]:
# 使用reshape()方法更改Numpy数组对象的形状
# 将一维数组更改为二维数组，三行五列
arr2 = arr.reshape((3,5))
print(arr)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [24]:
print("arr2的形状：\t",arr2.shape)
print("arr2的维度：\t",arr2.ndim)
print("arr2元素类型：\t",arr2.dtype)
print("arr2元素大小：\t",arr2.itemsize)
print("arr2元素个数：\t",arr2.size)
print("arr2的类型：\t",type(arr2))

arr2的形状：	 (3, 5)
arr2的维度：	 2
arr2元素类型：	 int32
arr2元素大小：	 4
arr2元素个数：	 15
arr2的类型：	 <class 'numpy.ndarray'>


### 2. Ndarray的创建

In [28]:
# array
# 使用array()函数创建一个一维的Ndarray对象
arr = np.array([1,2,3,4,5]) 
print(arr)
print(arr.dtype)
print(arr.shape)
print(type(arr))

[1 2 3 4 5]
int32
(5,)
<class 'numpy.ndarray'>


In [30]:
# 使用array()函数创建一个二位的Ndarray对象
arr2 = np.array([[1,2],[3,4]])
print(arr2)
print(arr2.dtype)
print(arr2.shape)
print(type(arr2))

[[1 2]
 [3 4]]
int32
(2, 2)
<class 'numpy.ndarray'>


In [36]:
# zeros/ones/empty
# 创建一个三行四列的二位Ndarray对象，并用0填充
arr = np.zeros((3,4))
print(arr)
print(arr.shape)
print(arr.dtype)

# 创建一个三行四列的Ndarray对象，并用1填充
arr2 = np.ones((3,4))
print(arr2)
print(arr2.shape)
print(arr2.dtype)

# 创建一个三行四列的Ndarray对象，不做填充
arr3 = np.empty((3,4))
print(arr3)
print(arr3.shape)
print(arr3.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
float64
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
float64
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
float64


In [41]:
# arange(start,stop,step)

# 创建一个区间为[0,20)步长为5的Ndarray一维对象
arr = np.arange(0,20,5,dtype=int)
print(arr)
print(arr.dtype)
print(type(arr))

[ 0  5 10 15]
int32
<class 'numpy.ndarray'>


In [44]:
# mat
# 利用mat将字符串形式的数据转为Ndarray对象
arr = np.mat('1 2;3 4')
print(arr)

arr2 = np.mat('1,2;3,4')
print(arr2)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [47]:
# matrix
# 利用matrix将列表转为Ndarray对象
arr = np.matrix([[1,2,3],[3,4,5]])
print(arr)

# ! 注意，matrix方法只能转换二维数组
# arr2 = np.matrix([[[1,2],[3,4]],[[1,2],[3,4]]])
# print(arr2)

[[1 2 3]
 [3 4 5]]


In [50]:
# random.rand(d0, d1, d2, ...)
# 利用random.rand()方法创建一个三维数组，数组元素区间为[0,1]
arr = np.random.rand(2,3,4)
print(arr)

[[[0.21940839 0.48251774 0.73357573 0.83631398]
  [0.05431324 0.8719793  0.36038504 0.65467463]
  [0.58193484 0.72776255 0.06402132 0.57276734]]

 [[0.89329744 0.90340171 0.20673328 0.20357587]
  [0.41006172 0.13206985 0.88299633 0.78372155]
  [0.43124691 0.34244934 0.82276054 0.32483358]]]


In [52]:
# random.randint(low,high,size)
# 使用random.randint创建一个取值范围在[-5,5]之间，尺寸为（3，4）的Ndarray对象
arr = np.random.randint(-5,5,size=(3,4))
print(arr)

[[ 1  3  2 -4]
 [ 3  2  0 -4]
 [ 0 -5 -5  0]]


In [54]:
# random.uniform(low, hight, size) # 均匀分布
# 在取值数量足够多的情况下，每个元素出现的概率会趋近相同
# 使用random.uniform函数创建一个取值在[-1,1]之间，尺寸为（3，4）的Ndarray对象
arr = np.random.uniform(-1,1,size=(3,4))
print(arr)

[[ 0.90470978 -0.71695084  0.1472858   0.09443497]
 [ 0.91643018  0.48656892 -0.51925846 -0.04505896]
 [-0.07455839 -0.48482815  0.40704756 -0.39300479]]


### 3. 等比/差数列

In [58]:
# logspace(start, stop, num, base)
# start和stop代表是base的幂次
# 当前案例取值范围为[2^0,2^7]，也就是[1,128]
# 从中等比的取出8个元素
# base默认为10
arr = np.logspace(0,7,8,base=2)
print(arr)

[  1.   2.   4.   8.  16.  32.  64. 128.]


In [60]:
# 从[10^0,10^10]中等比的取出11个元素，也就是[1,10,100,...,10^10]
arr = np.logspace(0,10,11)
print(arr)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09
 1.e+10]


In [64]:
# linespace(start, stop, num, endpoint)
# 从[0,10]区间中等差取出11个元素
arr = np.linspace(0,10,11)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [66]:
# linespace(start, stop, num, endpoint)
# 从[0,10)区间中等差取出11个元素
# endpoint表示不包含最后一个元素
arr = np.linspace(0,10,11,endpoint=False) 
print(arr)

[0.         0.90909091 1.81818182 2.72727273 3.63636364 4.54545455
 5.45454545 6.36363636 7.27272727 8.18181818 9.09090909]


In [128]:
# astype 类型转换
zeros1 = np.zeros((3,4))
print(zeros1.dtype)
zeros2 = zeros1.astype(np.int32)
print(zeros2.dtype)

float64
int32


### 4. 内置函数

In [67]:
# np.ceil()     # 向上取整
# np.floor()    # 向下取整
# np.rint()     # 四舍五入
# np.isnan()    # 是否为空
# np.multiply() # 元素相乘
# np.divide()   # 元素相除
# np.abs()      # 取绝对值
# np.where()    # 三目运算符

In [83]:
# randn和rand的区别在于randn是服从正太分布的
# 平均值为0，标准差为1
arr = np.random.randn(3,4)
print(arr)

[[ 1.7387864   0.21552634  0.01167621 -1.33103803]
 [-0.15434126 -1.49543689  0.81487399 -1.99554259]
 [ 0.1075364   2.72180515 -0.02743895  1.3434261 ]]


In [74]:
print(np.ceil(arr))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [75]:
print(np.floor(arr))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [77]:
print(np.rint(arr)) # 

[[1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [79]:
print(np.isnan(arr)) # 都不为空，都是False

[[False False False False]
 [False False False False]
 [False False False False]]


In [81]:
print(np.multiply(arr, arr))

array([[2.52530856e-01, 7.84625222e-02, 6.95888877e-04, 3.13761941e-01],
       [4.98143595e-02, 9.52324097e-01, 5.12084634e-01, 1.03128412e-01],
       [1.72294162e-01, 1.51219838e-02, 5.20106329e-02, 2.41213489e-01]])

In [85]:
print(np.divide(arr, arr)) # 对位相除

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [87]:
print(np.abs(arr))

[[1.7387864  0.21552634 0.01167621 1.33103803]
 [0.15434126 1.49543689 0.81487399 1.99554259]
 [0.1075364  2.72180515 0.02743895 1.3434261 ]]


In [89]:
print(np.where(arr>0,True,False))

[[ True  True  True False]
 [False False  True False]
 [ True  True False  True]]


In [90]:
# np.mean()     # 所有元素平均值
# np.sum()      # 所有元素的和
# np.max()      # 所有元素中的最大值
# np.min()      # 所有元素中的最小值
# np.std()      # 所有元素的标准差
# np.var()      # 所有元素的方差
# np.cumsum()   # 返回数组，每个元素都是前几个元素的累加
# np.cumprod()  # 返回数组，每个元素都是前几个元素的累乘


In [92]:
print(np.mean(arr))

0.16248607147827085


In [93]:
print(np.sum(arr))

1.94983285773925


In [94]:
print(np.max(arr))

2.721805145833712


In [95]:
print(np.min(arr))

-1.995542592774182


In [96]:
print(np.std(arr))

1.312011945436658


In [108]:
print(np.var(arr))
print(np.var(arr,axis=0))
print(np.var(arr,axis=1))

1.7213753449684839
[0.70149876 2.99932878 0.15068308 2.08255963]
[1.18520942 1.22587634 1.2323491 ]


In [104]:
print(arr,'\n')
# 每列元素都是前几列元素的和
print(np.cumsum(arr),'\n')

# 每行元素都是前几行元素的和
print(np.cumsum(arr,axis=0),'\n')

[[ 1.7387864   0.21552634  0.01167621 -1.33103803]
 [-0.15434126 -1.49543689  0.81487399 -1.99554259]
 [ 0.1075364   2.72180515 -0.02743895  1.3434261 ]] 

[ 1.7387864   1.95431274  1.96598895  0.63495092  0.48060965 -1.01482724
 -0.19995325 -2.19549584 -2.08795945  0.6338457   0.60640675  1.94983286] 

[[ 1.7387864   0.21552634  0.01167621 -1.33103803]
 [ 1.58444514 -1.27991055  0.82655019 -3.32658062]
 [ 1.69198154  1.44189459  0.79911124 -1.98315452]] 


In [106]:
print(arr,'\n')
print(np.cumprod(arr),'\n')
print(np.cumprod(arr,axis=0),'\n')

[[ 1.7387864   0.21552634  0.01167621 -1.33103803]
 [-0.15434126 -1.49543689  0.81487399 -1.99554259]
 [ 0.1075364   2.72180515 -0.02743895  1.3434261 ]] 

[ 1.73878640e+00  3.74754268e-01  4.37570773e-03 -5.82423339e-03
  8.98919546e-04 -1.34427745e-03 -1.09541672e-03  2.18595073e-03
  2.35069262e-04  6.39812728e-04 -1.75557867e-05 -2.35849022e-05] 

[[ 1.73878640e+00  2.15526339e-01  1.16762052e-02 -1.33103803e+00]
 [-2.68366492e-01 -3.22306038e-01  9.51463587e-03  2.65614308e+00]
 [-2.88591653e-02 -8.77254233e-01 -2.61071578e-04  3.56833195e+00]] 


### 5. 比较/去重/排序

In [111]:
arr = np.random.randn(2,3)
print(arr)

[[-0.34448949  0.28556633  0.00612457]
 [-0.47795757  1.00060211  0.91807622]]


In [113]:
np.any(arr>0.8)

True

In [115]:
np.all(arr>0.8)

False

In [117]:
arr = np.array([[1,2,1],[2,3,4]])
print(arr)

[[1 2 1]
 [2 3 4]]


In [121]:
np.unique(arr)

array([1, 2, 3, 4])

In [124]:
print(np.sort(arr)) # 返回一个新数组
print(arr)          # 不修改原值

[[1 1 2]
 [2 3 4]]
[[1 2 1]
 [2 3 4]]


In [125]:
arr.sort() # 直接修改原值
print(arr)

[[1 1 2]
 [2 3 4]]


### 6. 数学运算

In [144]:
arr = np.array([2,3,4,5])
brr = np.arange(4)

In [145]:
# +/-
print(arr-brr)
print(arr+brr)

[2 2 2 2]
[2 4 6 8]


In [146]:
brr = arr+1 # 每个元素都加1
brr

array([3, 4, 5, 6])

In [141]:
# 点乘
arr = np.array([[1,2],[3,4]])
brr = np.array([[4,3],[2,1]])
arr.dot(brr) # 矩阵乘法，不同于np.multiply

array([[ 8,  5],
       [20, 13]])